"""empty message

Revision ID: 25602d731834
Revises: 3b31cf386c83
Create Date: 2019-12-07 08:47:48.741411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25602d731834'
down_revision = '3b31cf386c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circles_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('circle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circles_members_circle_id'), 'circles_members', ['circle_id'], unique=False)
    op.create_index(op.f('ix_circles_members_user_id'), 'circles_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circles_members_user_id'), table_name='circles_members')
    op.drop_index(op.f('ix_circles_members_circle_id'), table_name='circles_members')
    op.drop_table('circles_members')
    # ### end Alembic commands ###
