"""empty message

Revision ID: 6327a3c8322f
Revises: 6e373200c67b
Create Date: 2019-12-01 19:52:37.961483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6327a3c8322f'
down_revision = '6e373200c67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('check_rule', sa.String(length=256), nullable=True),
    sa.Column('circle_master_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('joined_number', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circles')
    # ### end Alembic commands ###
